default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306
  pool: 5

development: &development
  <<: *default
  username: <%= ENV["TTA_DEV_USER"] %>
  password: <%= ENV["TTA_DEV_PASSWORD"] %>
  database: tta_dev

test: &test
  <<: *default
  username: <%= ENV["TTA_TEST_USER"] %>
  password: <%= ENV["TTA_TEST_PASSWORD"] %>
  database: tta_test

production:
  <<: *default
  database: tta_prod
  username: <%= ENV["TTA_PROD_USER"] %>
  password: <%= ENV["TTA_PROD_PASSWORD"] %>

cucumber:
  <<: *test