default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 3306

development: &development
  <<: *default
  pool: 5
  username: <%= ENV["TTA_DEV_USER"] %>
  password: <%= ENV["TTA_DEV_PASSWORD"] %>
  database: tta_dev

test: &test
  <<: *default
  pool: 5
  username: <%= ENV["TTA_TEST_USER"] %>
  password: <%= ENV["TTA_TEST_PASSWORD"] %>
  database: tta_test

production:
  adapter: mysql2
  encoding: utf8
  database: tta_prod
  pool: 5
  username: <%= ENV["TTA_PROD_USER"] %>
  password: <%= ENV["TTA_PROD_PWD"] %>
  host: localhost
  port: 3306

cucumber:
  <<: *test