require_relative  'seed_helper'
number_of_projects=2
number_of_subprojects_per_project=3
number_of_test_metadatum_per_subproject=10
number_of_test_suite_records_per_test_metadatum=15
number_of_test_case_records_per_test_suite_record=50

Seed::Helper.create_seed_data(number_of_projects, number_of_subprojects_per_project, number_of_test_metadatum_per_subproject, number_of_test_suite_records_per_test_metadatum, number_of_test_case_records_per_test_suite_record)